name: molgen

general:
  seed: 23

data:
  restart_preprocessing: False #If False all the files that have already been processed will be skipped. If a new attribute is added set this to True and rerun preprocessing.
  max_cores_preprocessing: 8 #Maximum number of cores used when preprocessing files.
  processed_data_path: data/processed/druglike-instock #
  debugging_data_path: data/debug/druglike-instock #Smaller subset of train data to make debugging faster
  general_path: data/processed/general/
  attribute_columns: ["logp","weight","qed","tpsa","sascore","sdx","sa","dga","dgp"] #["logp","weight","qed","tpsa","volume","sascore","deltag","sdc","sdx","sa","dga","dgp","dgtot"]

training:
  cuda_device: 0 # Specifies the cuda device to run the code on. If there is only 1 GPU set this to 0.
  data_loader_workers: 8 # Number of workers for the dataloader

gct:
  restart_training: True #If False the previous model will be loaded and training will continue. If a new attribute or hyperparameters are changes set this to True and rerun training.
  preload_weights: False #If previous weights should be loaded, even though training is restartet.
  preload_weights_name: pretrained_enc6_dec6_0.pt #The name of the weights to be loaded if load_previous_weights is true.
  preload_weights_strict: False #If the networks should be exactly the same or if it can load only the ones matching and not throw error if the network are not exactly the same
  batch_size: 32 #Training batch size.
  num_epochs: 25 #Number of epochs the model trains.
  n_encoder_blocks: 6 #Number of encoder blocks in the transformer
  n_decoder_blocks: 6 #Number of decoder blocks in the transformer
  d_model: 512 #Embedding dimension.
  d_ff: 1024 #Feed forward dimension in the feedforward layer of the transformer.
  d_latent_space: 128 #Dimension of the latent space of the transition from the encoder to the decoder.
  n_mha_heads_encoder: 8 #Number of heads in the multi headed attention layer for encoder.
  n_mha_heads_decoder: 8 #Number of heads in the multi headed attention layer for decoder.
  dropout: 0.3 #Dropout percentage.
  normalizer_eps: 0.000001 #Normalization epsilon to make sure that we do not divide by 0.
  include_bias: True #Wether to include bias in the torch layers.
  initial_lr: 0.0001 # Initial LR of the optimizer.
  optimizer_beta1: 0.9 # Beta 1 of the Adam optimizer
  optimizer_beta2: 0.98 # Beta 2 of the Adam optimizer
  lr_scheduler_factor: 0.7 #The factor parameter defines the reduction factor by which the learning rate will be multiplied (e.g., 0.2 means a 80% reduction)
  lr_scheduler_patience: 10 #The patience of the scheduler, which is the number of epochs where there has to be no change before it reduces lr. 
  lr_schedule_min_lr: 0.000001 #The minimum learning rate of the scheduler.
  kla_initial_beta: 0.1 #KL Annealing initial beta, which is the weighting og the kl divergence in the loss function
  kla_increment_beta: 0.1 #The incrementation of the beta, how much it increases. 
  kla_max_beta: 30 #Maximum beta
  kla_beginning_step: 1 #The step where kl annealing is starting. 
  kla_increment_steps: 10000 #How often to increase the kla. If batch size of 64 there is 95000 steps pr epoch.
  orth_initial_gamma: 0.0003 #Orthoganl Annealing initial gamma, which is the weighting of the orthognality loss of the latent space. 
  orth_increment_gamma: 0.00005 #The incrementation of the gamma, how much it increases pr. epoch.
  orth_max_gamma: 0.02 #Maximum weighting of orthogonal loss
  orth_beginning_step: 1 #The epoch where orthogonal annealing starts
  orth_increment_steps: 10000 #How often to increase the orth annealing. If batch size of 64 there is 95000 steps pr epoch.
  attr_initial_theta: 0.075 #Attribute Annealing initial theta, which is the weighting of the attribute loss in the loss function
  attr_increment_theta: 0.001 #The incrementation of the theta, how much it increases. 
  attr_max_theta: 1 #Maximum theta
  attr_beginning_step: 1 #The step where attribute annealing is starting. 
  attr_increment_steps: 10000 #How often to increase the attribute theta. If batch size of 64 there is 95000 steps pr epoch.
  include_conditions_encoder: False #If the conditions should be concatenated with the smile molecule in the encoder.
  include_conditions_decoder: True #If the conditions should be concatenated with the smile in the decoding of the model.
  include_conditions_reparameterization: True #If the conditions should be concatenated after the reparameterization of the encoder.
  save_model_epoch: 1 #When to save the model, if this is 1 it will save the model after each epoch.
  model_save_path: models/gct/
  debugging: False #If true this will only train on a small subset of the data and then return.
  generation_method: "beam_search" #The method used to generate molecules. Options: "beem_search", "greedy_search"
  beam_width: 10 #The width of the beam search.
  beam_search_alpha: 0.85 #Length normalization, if alpha=1 then it will be normalized by length, if alpha=0 no normalization.
  attribute_scaler: standard #The scaler used for the attributes. Can be minmax, standard and None.
  generated_smiles_path: data/generated/gct_generated

gct_hyperoptim:
  eval_n_molecules_generated: 1000 #Number of molecules each model generates to evaluate the model.
  eval_n_molecules_pr_condition: 32 #Number of molecules each condition combination generates to evaluate the model.
  eval_generation_method: "beam_search" #The method used to generate molecules for evaluation. Options: "beam_search", "greedy_search"
  eval_condition_noise: 0.01 #The scaler of the noise added to the conditions.
  eval_loss_validation_rce_weight: 150 #The weight of the validation rce loss in the hyperparameter optimization. These are on a scale of around 0.01, so weight should be bigger.
  eval_loss_validation_kl_weight: 150 #The weight of the validation loss in the hyperparameter optimization. These are on a scale of around 0.005, so weight should be bigger.
  eval_loss_validation_orth_weight: 0.005 #The weight of the validation loss in the hyperparameter optimization. These are on a scale of around 1-2, so weight should be smaller.
  eval_loss_validity_weight: 0.5 #The weight of the validity loss in the hyperparameter optimization.
  eval_loss_novelty_weight: 0.5 #The weight of the novelty loss in the hyperparameter optimization.
  eval_loss_uniqueness_weight: 1 #The weight of the uniqueness loss in the hyperparameter optimization.
  eval_loss_validation_attribute_weight: 1 #The weight of the attribute loss in the hyperparameter optimization.
  eval_loss_attribute_accuracy_weight: 2 #The weight of the attribute accuracy loss in the hyperparameter optimization.
  save_models: True #If each model should be saved during the hyperparameter optimization.
  study_name: gct_hyperoptim_study #The name of the hyperparameter optimization study.
  study_path: models/gct/gct_hyperoptim_study.pkl #The path where the hyperparameter optimization study is saved.
  restart_study: False #If the study should be restarted or continued.
  n_study_runs: 100 #The number of trials in the hyperparameter optimization study before the script ends.

evaluation:
  eval_n_molecules_generated: 30000 #Number of molecules each model generates to evaluate the model.
  eval_n_molecules_pr_condition: 1 #Number of molecules each condition combination generates to evaluate the model.
  eval_generation_method: "beam_search" #The method used to generate molecules for evaluation. Options: "beam_search", "greedy_search"
  eval_condition_noise: 0.01 #The scaler of the noise added to the conditions.
  eval_confidence_interval_n: 1000

wandb:
  WANDB_KEY: 0048a0aaf97e866f52771a3de5fc219094beceb7
  entity: markussorensen
  log_n_steps: 1000 #Log every n steps

styleclip: #Styleclip hyperparams for generating new molecules.
  model_path: pretrained_enc6_dec6_nocondition_7.pt #The name of the model used for generating new molecules.
  attribute_predictor_path: attribute_predictor_enc6_1.pt
  use_gct_hyperparams: True #If the hyperparams from the current configuration of the gct model should be used. These need to fit the model that is loaded from path/type. 
  #["logp","weight","qed","tpsa","volume","sascore","deltag","sdc","sdx","sa","dga","dgp","dgtot"]
  target_attributes: {"logp": 4.071700000000002,
                      "weight": 300,
                      "qed": max,
                      "tpsa": 37.3,
                      "volume": 300,
                      "sascore": min,
                      "deltag": -88,
                      "sdc": 5.1633,
                      "sdx": 0.7968,
                      "sa": 1.8972,
                      "dga": -12.8046,
                      "dgp": -45.0341,
                      "dgtot": -88} #The target attributes wanted from generating smiles. Be aware that only the ones in data.attribute_columns will be used, as the model is only trained to these. Therefor it wont change anything changing the other values.
  target_weighting: {"logp": 1,
                      "weight": 0.5,
                      "qed": 1,
                      "tpsa": 0.5,
                      "volume": 0,
                      "sascore": 2,
                      "deltag": 0,
                      "sdc": 0.2,
                      "sdx": 0.2,
                      "sa": 0.2,
                      "dga": 0.2,
                      "dgp": 0.2,
                      "dgtot": 0} #The weighting of the different attributes (the importance). The score just has to be relative to eachother.
  z_initialization_method: sample #This can be sample (sampling a random point from a standard normal distribution), zero (starting point just 0's, middle of the latent space), molecule (starting point is the molecule from below.)
  initial_molecule: O=C1c2ccccc2C(O)=C1c1ccc(Br)cc1 #Here a smile can be written from data set, if this is done the corresponding z (latent space representation) of this smile will be used as starting point. If smile is not found the normal initialization method is used.
  n_epochs: 200 #Number of iterations before terminating.
  log_each_n_iters: 10 #Saves an image of the molecule with its attributes each log_each_n_iters iterations.
  lr: 0.1 #Initial learning rate of optimizer
  lr_patience: 10 #Patience of LR scheduler
  lr_mul_factor: 0.8 #The factor parameter defines the reduction factor by which the learning rate will be multiplied (e.g., 0.2 means a 80% reduction)
  generation_method: "beam_search" #The method used to generate molecules for evaluation. Options: "beam_search", "greedy_search"
  generated_smiles_path: data/generated/styleclip_generated

ctd:
  restart_training: True #If False the previous model will be loaded and training will continue. If a new attribute or hyperparameters are changes set this to True and rerun training.
  preload_weights: False #If previous weights should be loaded, even though training is restartet.
  preload_weights_name: ehm.pt #The name of the weights to be loaded if load_previous_weights is true.
  preload_weights_strict: True #If the networks should be exactly the same or if it can load only the ones matching and not throw error if the network are not exactly the same
  batch_size: 32 #Training batch size.
  num_epochs: 25 #Number of epochs the model trains.
  n_decoder_blocks: 10 #Number of decoder blocks in the transformer
  d_model: 512 #Embedding dimension.
  d_ff: 2048 #Feed forward dimension in the feedforward layer of the transformer.
  n_mha_heads_decoder: 8 #Number of heads in the multi headed attention layer for decoder.
  dropout: 0.2 #Dropout percentage.
  normalizer_eps: 0.000001 #Normalization epsilon to make sure that we do not divide by 0.
  include_bias: True #Wether to include bias in the torch layers.
  initial_lr: 0.0001 # Initial LR of the optimizer.
  optimizer_beta1: 0.9 # Beta 1 of the Adam optimizer
  optimizer_beta2: 0.98 # Beta 2 of the Adam optimizer
  lr_scheduler_factor: 0.2 #The factor parameter defines the reduction factor by which the learning rate will be multiplied (e.g., 0.2 means a 80% reduction)
  lr_scheduler_patience: 5 #The patience of the scheduler, which is the number of epochs where there has to be no change before it reduces lr. 
  lr_schedule_min_lr: 0.000001 #The minimum learning rate of the scheduler.
  save_model_steps: 10000 #When to save the model, if this is 1 it will save the model after each epoch.
  model_save_path: models/ctd/
  debugging: False #If true this will only train on a small subset of the data and then return.
  generation_method: "beam_search" #The method used to generate molecules. Options: "beem_search", "greedy_search"
  beam_width: 10 #The width of the beam search.
  beam_search_alpha: 0.85 #Length normalization, if alpha=1 then it will be normalized by length, if alpha=0 no normalization.
  attribute_scaler: standard #The scaler used for the attributes. Can be minmax, standard and None.
  generated_smiles_path: data/generated/ctd_generated

attribute_predictor:
  attribute_weights: [1,1,1.5,1,1.5,0.5,0.5,0.5,0.5] #Weights of the columns in data attribute columns ["logp","weight","qed","tpsa","sascore","sdx","sa","dga","dgp"]
  n_epochs: 25